### ISSUE TITLE
Missing eslintrc rule linebreaks for windows platform

### ISSUE THREAD

**Issue by IslandOfCode** [LanceGin/Mockman#2]
Building from source on windows platform (_Windows 10 x64_), `npm run build` return this error:
`Expected linebreaks to be 'LF' but found 'CRLF'`

Adding the following rules to `.eslintrc` file fix the issue:
```
'rules': {
	"linebreak-style": 0,
	"eslint linebreak-style": [0,"error","windows"],
...
```

**Comment by LanceGin** [comment]
I've added the specific rule to `.eslintrc` file on the `dev` branch. You can switch to dev branch to pull it. 

That will be merged to `master` branch when next version is released.
