### ISSUE TITLE
[Feature Request] Dynamic responses, Custom error response Advance Logging

### ISSUE THREAD

**Issue by uniibu** [LanceGin/Mockman#3]
**Dynamic responses** 
I'd like to request additional feature to be able to mock a server and respond dynamically based on parameters.

Excample scenario of this request:
- I create a mock server running on `localhost:3000/api/getinfo` with a params of `user`
- Then i could add a simple json record where the app could get the info from.
- Then on response tab, i can put something like `{ "success": true, "data": $user }`
- The mock server will then get the `data` part on the given json based on the given params.

**Custom error response**
- The current setup is when a params is given and it is missing from the request, it will respond with `{"errors":[{"key":"user","details":"required params."}]}`
- It would nice if the user is able to customize this respond on every route.

**Advance Logging**
- It would be nice to have something like an advance tab where user can view the actual request that was received. Something similar to this image
![image](https://i.gyazo.com/602b356a4c0e229121bf9ffa65e3566e.png)

Thanks!

**Comment by LanceGin** [comment]
Sorry, `Dynamic responses` && `Custom error response` will not be added to Mockman in the future version. In fact Mockman is a mock tool to help us developing our product fluently, we shouldn't denpend on it to do some test about our `Specific business`.

`Advance Logging` is a good idea, I will add a `logging panel` to every `running server` in the future.

**Comment by LanceGin** [comment]
A new logging panel has been added to Mockman version `1.0.4`.

![Logger](https://i.loli.net/2018/11/03/5bdd4deac142f.png)
