### ISSUE TITLE
[BUG] Does not allow direct query parameters

### ISSUE THREAD

**Issue by uniibu** [LanceGin/Mockman#5]
Mockman does not allow setting query parameters on the path section. If you add a query parameter, the path does not work.

An example:
Side to side screenshot of Mockman as the mock server and Postman as the client.
![Image](https://i.gyazo.com/3f26f08899dc41adb8ddd1ba3e02a5d2.png)

Suggestion:
- Allow user to direct input the query parameters on the path field, and automatically add it on the request's Param section.
- Also it would be nice to allow user to set a static value for those params and only accept requests if the  parameters are the same value.

**Comment by LanceGin** [comment]
Mockman is a dev tool, so a specific query parameter is not recommended.
