### ISSUE TITLE
[Bug] Does not accept Body other than application/json and multipart/form-data

### ISSUE THREAD

**Issue by uniibu** [LanceGin/Mockman#6]
Mockman does not accept a valid body request unless the content-type of the request is `application/json`  or `multipart/form-data`.

At the very least, it should also accept request's body which content-type is `application/x-www-form-urlencoded`. Check the screenshot below:
![image](https://i.gyazo.com/c5ab00dd65251a31aa4b7901fdb2c6f6.png)

**Comment by LanceGin** [comment]
Version `1.0.3` has solved this problem.
