### ISSUE TITLE
[Bug] Case-sensitive headers

### ISSUE THREAD

**Issue by uniibu** [LanceGin/Mockman#7]
When you set a header on the `Request` tab with something like `X-Custom-Token` and the client requests with a header of either `X-Custom-Token` or `x-custom-token`, Mockman will not recognize any of those. Check the postman screenshot below.
Capitalized first letter header
![image1](https://i.gyazo.com/1e3dc0b0620efa568a3f432af852039f.png)
Lower-cased header
![image2](https://i.gyazo.com/d798a979609ab801ed56723a29d837dd.png)

As according to the official specs [rfc7231](https://tools.ietf.org/html/rfc7230#section-3.2) 
```
3.2.  Header Fields
   Each header field consists of a case-insensitive field name followed
   by a colon (":"), optional leading whitespace, the field value, and
   optional trailing whitespace.
```

Therefor, Mockman should accept valid header fields regardless of its letter-case.

Note:
Mockman accepts case-insensitive headers **only if** the header on the `Request` is set to all lower-case.

**Comment by LanceGin** [comment]
Thanks for the issue, the problem has been solved in the new `1.0.2` version

Details : [code](https://github.com/LanceGin/Mockman/commit/d853298592d6ba3f8bd8cb7cbea61961d57993f0)
